services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: unless-stopped  # 改为unless-stopped以避免意外重启
    hostname: 'gitlab.localhost'
    entrypoint: ["/bin/sh", "-c", "/root/patch/repatch.sh && exec /assets/init-container"] #  
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://127.0.0.1'
        gitlab_rails['elasticsearch_enabled'] = true
        gitlab_rails['elasticsearch_url'] = ['http://elasticsearch:9200']
        gitlab_rails['elasticsearch_indexer_enabled'] = true
        gitlab_rails['elasticsearch_aws'] = false
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - './patch:/root/patch'
    shm_size: '1G'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - TZ=Asia/Shanghai
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"  # 减少内存使用
    # Uncomment the following lines to persist data, config, logs, and plugins
    # volumes:
    #   - ./elasticsearch/data:/usr/share/elasticsearch/data
    #   - ./elasticsearch/config:/usr/share/elasticsearch/config
    #   - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    #   - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins 
    ports:
      - '9200:9200'
      - '9300:9300'
    deploy:
      resources:
        limits:
          memory: 512MiB  # 减少内存限制从1GiB到512MiB
          cpus: '1'       # 限制CPU使用
  
