services:
  gitlab:
    image: gitlab/gitlab-ee:18.3.0-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.localhost'
    entrypoint: ["/bin/sh", "-c", "/root/patch/repatch.sh && exec /assets/init-container"] #  
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://127.0.0.1'
        gitlab_rails['elasticsearch_enabled'] = true
        gitlab_rails['elasticsearch_url'] = ['http://elasticsearch:9200']
        gitlab_rails['elasticsearch_indexer_enabled'] = true
        gitlab_rails['elasticsearch_aws'] = false
        gitlab_rails['allow_local_requests_from_web_hooks_and_services'] = true
        gitlab_rails['allow_local_requests_from_system_hooks'] = true
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - './patch:/root/patch'
    shm_size: '1G'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - TZ=Asia/Shanghai
      - xpack.security.enabled=false
    # Uncomment the following lines to persist data, config, logs, and plugins
    # volumes:
    #   - ./elasticsearch/data:/usr/share/elasticsearch/data
    #   - ./elasticsearch/config:/usr/share/elasticsearch/config
    #   - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    #   - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins 
    ports:
      - '9200:9200'
      - '9300:9300'
    deploy:
      resources:
        limits:
          memory: 1GiB
    #       cpus: '4'
  
  # 写一个能够debug客户端网络请求的web server docker容器
  debugserver:
    build:
      context: ./debug-server
      dockerfile: Dockerfile.debugserver
    container_name: debugserver
    restart: always
    ports:
      - '8081:80'
  # 能不能写一个模拟的域名 比如 test.gitlab.localhost 让gitlab能访问到debugserver
  # 不要带ip
    networks:
      default:
        aliases:
          - customers.ayaka.space
